- hosts: all
  vars:
    # Directories
    bin_dir: "{{ ansible_user_dir }}/bin"
    source_dir: "{{ ansible_user_dir }}/src"
    install_dir: "{{ ansible_user_dir }}/R"

    # R
    r_version: 3.6.1
    r_url: https://cran.r-project.org/src/base/R-3/R-{{ r_version }}.tar.gz
    # The filters below strip URL and file ending to get correct path from r_url
    r_source_dir: "{{ source_dir }}/{{ r_url | basename | splitext | first | splitext | first }}"
    r_install_dir: "{{ install_dir }}/{{ r_url | basename | splitext | first | splitext | first }}"

    # SAIGE
    saige_version: 0.36.1
    saige_release_url: "https://github.com/weizhouUMICH/SAIGE/releases/download/{{ saige_version }}/SAIGE_{{ saige_version }}_R_x86_64-pc-linux-gnu.tar.gz"
    saige_dependency_url: "https://raw.githubusercontent.com/weizhouUMICH/SAIGE/{{ saige_version }}/extdata/install_packages.R"
    saige_dir: "{{ source_dir }}/SAIGE"

    # Make Ansible use Python 3
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
  - name: Create directories
    file:
      path: "{{ item }}"
      state: directory
    loop:
      - "{{ bin_dir }}"
      - "{{ source_dir }}"
      - "{{ install_dir }}"
      - "{{ saige_dir }}"


  # R
  - name: Install apt dependencies for compiling R {{ r_version }}
    apt:
      name:
        - gcc
        - g++
        - tcl-dev
        - tk-dev
        - libopenblas-dev
        - libbz2-dev
        - liblzma-dev
        - libpcre3-dev
        - libcurl4-openssl-dev
        - libreadline-dev
      install_recommends: no
    become: yes

  - name: Download and extract R {{ r_version }} to {{ r_source_dir }}
    unarchive:
      src: "{{ r_url }}"
      dest: "{{ source_dir }}"
      creates: "{{ r_source_dir }}"
      remote_src: yes

  - name: Configure R {{ r_version }}
    command: >
      ./configure
      --prefix={{ r_install_dir }}
      --with-x=no
      --enable-memory-profiling
      --enable-R-shlib
      --with-blas
      --enable-shared
      --with-tcltk
      --with-tcl-config=/usr/lib/tclConfig.sh
      --with-tk-config=/usr/lib/tkConfig.sh
      --with-libtiff
      --with-libpng
      --with-jpeglib
    args:
      chdir: "{{ r_source_dir }}"
      creates: "{{ r_source_dir }}/Makefile"

  - name: Make R {{ r_version }}
    make:
      chdir: "{{ r_source_dir }}"
      target: -j{{ ansible_processor_vcpus }}

  - name: Install R {{ r_version }}
    make:
      chdir: "{{ r_source_dir }}"
      target: install

  - name: Symlink R {{ r_version }} binaries to {{ bin_dir }}
    file:
      src: "{{ r_install_dir }}/bin/{{ item }}"
      dest: "{{ bin_dir }}/{{ item }}"
      state: link
    loop:
      - R
      - Rscript


  # SAIGE
  - name: Install apt dependencies for SAIGE {{ saige_version }}
    apt:
      name:
        - python3-dev
        - python3-pip
        - python3-setuptools
        - cmake
        - libgit2-24
        - libssl-dev
      install_recommends: no
    become: yes

  - name: Install pip dependencies for SAIGE {{ saige_version }}
    become: yes
    pip:
      name: cget

  - name: Download SAIGE {{ saige_version }} release
    get_url:
      url: "{{ saige_release_url }}"
      dest: "{{ saige_dir }}"

  # Slight workaround to get the SAIGE dependency install script
  # The SAIGE repository is large and we only need this file 
  - name: WORKAROUND - Check if SAIGE R dependencies installer exists
    stat:
      path: "{{ saige_dir }}/{{ saige_dependency_url | basename }}"
    register: dependency_stat_result

  - name: Download SAIGE {{ saige_version }} R dependencies installer
    get_url:
      url: "{{ saige_dependency_url }}"
      dest: "{{ saige_dir }}"
    when: not dependency_stat_result.stat.exists

  # Workaround for https://github.com/weizhouUMICH/SAIGE/pull/147
  - name: WORKAROUND - Change CRAN repo in SAIGE {{ saige_version }} R dependencies installer
    replace:
      path: "{{ saige_dir }}/{{ saige_dependency_url | basename }}"
      regexp: "http://cran.us.r-project.org"
      replace: "https://cloud.r-project.org"

  - name: Install SAIGE {{ saige_version }} R dependencies
    command: >
      {{ bin_dir }}/Rscript {{ saige_dir }}/{{ saige_dependency_url | basename }}
    args:
      # Check if MetaSKAT is installed which is last dependency
      creates: "{{ r_install_dir }}/lib/R/library/MetaSKAT"

  # Workaround for https://github.com/weizhouUMICH/SAIGE/issues/139#issuecomment-590100686
  - name: WORKAROUND - Check if SPAtest is installed
    stat:
      path: "{{ r_install_dir }}/lib/R/library/SPAtest/DESCRIPTION"
    register: spatest_stat_result

  - name: WORKAROUND - Check if SPAtest version 3.0.0 is installed
    lineinfile:
      path: "{{ r_install_dir }}/lib/R/library/SPAtest/DESCRIPTION"
      line: "Version: 3.0.0"
      state: present
    when: spatest_stat_result.stat.exists
    register: spatest_version
    check_mode: yes
    failed_when: no

  - name: WORKAROUND - Remove new SPAtest and install version 3.0.0
    command: >
      {{ bin_dir }}/R -e 'remove.packages("SPAtest"); install.packages("https://cran.r-project.org/src/contrib/Archive/SPAtest/SPAtest_3.0.0.tar.gz", repos=NULL, type="source")'
    # lineinfile output sets changed to true if the correct version is not present 
    when: spatest_version.changed

  - name: Install SAIGE {{ saige_version }}
    command: >
      {{ bin_dir }}/R CMD INSTALL {{ saige_dir }}/{{ saige_release_url | basename }}
    args:
      creates: "{{ r_install_dir }}/lib/R/library/SAIGE"


  # Extra R packages
  - import_tasks: extra-packages.yaml


  # Docker specifics
  - name: Symlink R {{ r_version }} binaries to /usr/local/bin for docker
    file:
      src: "{{ r_install_dir }}/bin/{{ item }}"
      dest: "/usr/local/bin/{{ item }}"
      state: link
    loop:
      - R
      - Rscript
    become: yes
    tags: never, docker

  - name: Clean up directories for docker
    file:
      path: "{{ item }}"
      state: absent
    loop:
      - "{{ source_dir }}"
      - /var/lib/apt/lists/
    become: yes
    tags: never, docker
